Fix legacy diagnostic for `Display`-like macros (#288)
Related to #225

## Synopsis

Diagnostic introduced in #225 regarding old syntax usage, displays
incorrect message in case formatting arguments are specified as
identifiers (not string literals):

```rust
#[derive(derive_more::Display)]
#[display(fmt = "Stuff({}): {}", _0)]
pub struct Bar(String);
```

```
error: unknown attribute, expected `bound(...)`
 --> tests/compile_fail/display/legacy_fmt_syntax.rs:8:11
  |
8 | #[display(fmt = "Stuff({}): {}", _0)]
  |           ^^^
```

In my experience, this situation happens very often in the wild.


## Solution

Fix the diagnostic to consider ident formatting arguments properly.